// app/components/MoviesList.jsx
"use client";
import Movie from "./Movie";
import { Fragment, useEffect, useRef, useState } from "react";

const MoviesList = (props) => {
  const moviesList = props.movies;
  const take = 4;
  const [loaded, setLoaded] = useState(0);
  const [movies, setMovies] = useState([]);
  const observed = useRef();

  const callback = (entries) => {
    if (entries[0].isIntersecting) {
      setLoaded((prevLoad) => prevLoad + take);
    }
  };

  // trigger only once when the page is rendered to create the intersection observer
  // and observe the ref
  useEffect(() => {
    console.log("creating intersection observer");
    const observer = new IntersectionObserver(callback, { threshold: 0.3 });
    observer.observe(observed.current);
  }, []);

  // trigger when loaded is updated by the intersection observer callback
  useEffect(() => {
    setMovies((prevMovies) => [
      ...prevMovies,
      ...moviesList.slice(loaded, loaded + take),
    ]);
  }, [loaded]);

  return (
    <Fragment>
      {movies.map((movie) => (
        <Movie
          title={movie.title}
          year={movie.year}
          director={movie.director}
          runningTime={movie.runningTime}
          trailerLink={movie.trailerLink}
          thumbPath={props.imgStorageUrl + movie.thumbPath}
          synopsis={movie.synopsis}
          categories={movie.categories}
          key={movie.id}
        />
      ))}
      <div ref={observed} />
    </Fragment>
  );
};

export default MoviesList;

// src/lib/components/MoviesList.svelte
<script>
	import Movie from '$lib/components/Movie.svelte';
	import { onMount } from 'svelte';
	let { movies, imgStorageUrl } = $props();
	let take = 2;
	let loaded = 0;
	let lastElement;
	let loadedMovies = $state([]);

	onMount(() => {
		const callback = (entries) => {
			if (entries[0].isIntersecting) {
				loaded += take;
				loadedMovies = Array.from(movies).slice(0, loaded);
				observer.unobserve(lastElement);
				observer.observe(lastElement);
			}
		};
		let observer = new IntersectionObserver(callback, { threshold: 0.3 });
		observer.observe(lastElement);
	});
</script>

{#each loadedMovies as movie (movie.id)}
	<Movie
	    id={movie.id}
		title={movie.title}
		year={movie.year}
		director={movie.director}
		runningTime={movie.runningTime}
		trailerLink={movie.trailerLink}
		thumbPath={imgStorageUrl + movie.thumbPath}
		synopsis={movie.synopsis}
		categories={movie.categories}
	/>
{/each}
<div bind:this={lastElement}></div>
